import Head from 'next/head'
export default function Main() {
  return (
    <div>
      <Head>
        <title>germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <navbar>
          <a href={"/blog"}>Blog</a>
        </navbar>
        <h1>Hola mundosjsjs</h1>
      </main>
    </div>
  );
} 