import Head from 'next/head'
import styles from '../styles/Home.module.css'
export default function Main() {
  return (
    <body className={styles.update}>
      <Head>
        <title>Actualizando</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>Updating/Actualizando</h1>
        <p>- German Ruiz</p>
      </main>
    </body>
  );
} 